### ISSUE TITLE
Возможно ли использовать другую СУБД кроме как Sybase ?

### ISSUE THREAD

**Issue by SergeyWegner** [YuriyKozin/WRM#1]
Возможно ли использовать другую СУБД кроме как Sybase ?, Например MySQL или PostgreSQL

**Comment by YuriyKozin** [comment]
добрый день. да, возможно! но с учетом того, что хостер позволит создавать процедуры в БД, что засто запрещается. сейчас занимаюсь переносом на MySQL для любых хостеров (без процедур)


Воскресенье, 08 марта 2015, 21:08 -07:00 от SergeyWegner <notifications@github.com>:

**Comment by SergeyWegner** [comment]
У Вас получилось?

**Comment by YuriyKozin** [comment]
да, получилось. система работает на mysql, просто сюда не выкладывал. посмотреть можно тут: http://jdesk.ru
